services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pruebas_ptt_php84
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8001:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: pruebas
      DB_USERNAME: wilfredo
      DB_PASSWORD: "Galadriel94*"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: pruebas_ptt_postgres
    environment:
      POSTGRES_DB: pruebas
      POSTGRES_USER: wilfredo
      POSTGRES_PASSWORD: "Galadriel94*"
    ports:
      - "5433:5432"
    volumes:
      - pruebas_ptt_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pruebas_ptt_postgres_data: